// <auto-generated />
using System;
using CaptchaApp.Server.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CaptchaApp.Server.Migrations
{
    [DbContext(typeof(CaptchaContext))]
    [Migration("20201007204337_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CaptchaApp.Server.Models.CaptchaDataSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnswerPlacement")
                        .HasColumnType("int");

                    b.Property<bool>("CaseSentence")
                        .HasColumnType("bit");

                    b.Property<bool>("ContainsCyrillic")
                        .HasColumnType("bit");

                    b.Property<bool>("ContainsDigits")
                        .HasColumnType("bit");

                    b.Property<bool>("ContainsLatin")
                        .HasColumnType("bit");

                    b.Property<bool>("ContainsSpecialSymbols")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ImagesZipFilename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataSets");
                });
#pragma warning restore 612, 618
        }
    }
}
